name: test_the_things

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install gtest submodule
      run: git submodule update --init
    - uses: actions/checkout@v1
      with: 
        submodules: true
    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-Werror"  ..
    - name: make
      run: cd build && make
    - name: Run Test
      run: build/Tests/Google_Tests_run
